version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DELFT3D_BIN_PATH=/opt/delft3d/bin
      - GEE_SERVICE_ACCOUNT=
    volumes:
      - ./backend/exports_storage:/app/backend/exports_storage

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
